#!/bin/bash

echo "🎯 Element Hider Setup - Usage Examples"
echo "======================================="
echo ""

echo "📖 Available modes:"
echo ""
echo "1. NORMAL MODE (default):"
echo "   ./setup.sh"
echo "   ./setup.sh --normal"
echo "   • Automatically applies existing element hiding rules"
echo "   • Best for production use and automation"
echo "   • Lightweight - no interactive features"
echo ""

echo "2. CONFIGURATION MODE:"
echo "   ./setup.sh --config"
echo "   ./setup.sh -c"
echo "   • Interactive element picker (like uBlock zapper)"
echo "   • Full CLI for rule management"
echo "   • Best for creating and testing hiding rules"
echo ""

echo "3. HELP:"
echo "   ./setup.sh --help"
echo "   ./setup.sh -h"
echo "   • Show detailed usage information"
echo ""

echo "🎨 Typical Workflow:"
echo "==================="
echo ""
echo "1. First time setup (create rules):"
echo "   ./setup.sh --config"
echo "   # Use picker mode to select elements to hide"
echo "   # Rules automatically saved to element_hiding_config.json"
echo ""

echo "2. Production use (apply rules):"
echo "   ./setup.sh"
echo "   # Rules applied automatically without interaction"
echo ""

echo "3. Add more rules later:"
echo "   ./setup.sh --config"
echo "   # Add new rules or modify existing ones"
echo ""

echo "📋 Configuration File:"
echo "====================="
echo "Rules stored in: element_hiding_config.json"
echo "Format: JSON with domain -> CSS selector mapping"
echo ""

echo "🚀 Quick Start:"
echo "==============="
echo "Choose your mode and run:"
echo ""
echo "For configuration: ./setup.sh --config"
echo "For normal use:    ./setup.sh"
echo ""

read -p "Press Enter to continue..." 